server:
 port: 80
 servlet: 
  session: 
   timeout: -1
spring:
 datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/pmdb?serverTimezone=UTC
  username: root
  password: root2019
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
  properties:
   hibernate:
    enable_lazy_load_no_trans: true
logging:
 config: "classpath:logback-spring.xml"
mail:
 host: krrelay.corp.doosan.com
 from: notice_cn@doosan.com
 #多人以逗号隔开
 user:
  to: guoqian.cheng@doosan.com